# Generated by Django 4.0.4 on 2022-06-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_forum', '0002_alter_images_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='forum',
            new_name='new',
        ),
    ]
